[project]
authors = ["Christopher Nair <chrisnair1@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ubuntu-rfd900-cli"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]


