[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rfd900-cli"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
click = ">=8.1.7,<9"
pyserial = ">=3.5,<4"
